### ISSUE TITLE
Icon Request: JSON Template

### ISSUE THREAD

**Issue by krabbypattified** [file-icons/source#10]
Requesting an icon for (SquareSpace's) JSON-Template files.
Below are relevant file-types, an Atom language package, and links explaining what JSON-T is.

file types: ".item" ".list" ".block"
apm package: language-jsont
http://jsont.squarespace.com/
https://developers.squarespace.com/what-is-json-t/

**Comment by Alhadis** [comment]
Easy. On it.

**Comment by Alhadis** [comment]
@krabbypattified I'll use the SquareSpace logo as the icon, will that suffice?

Also, are there any other file-extensions we can hook this onto? Config files, for example?

**Comment by krabbypattified** [comment]
There's template.conf, other .conf files, (for Squarespace site configuration) and .region files (sort of like index.php in Wordpress)

Would prefer an icon indicating it's a templating file, or just an HTML5 icon, or a Squarespace icon as you suggested. I'm sort of a beginner with Squarespace development, so I can't offer much more advice. Just use good design judgement :)

Thanks

**Comment by krabbypattified** [comment]
But leaving .conf files as you have them now is fine.

**Comment by Alhadis** [comment]
Yikes. I just had a look at the [`language-jsont`](https://github.com/stormwarning/language-jsont#language-jsont) package... the file-extensions they mention each sound worryingly generic:

> Adds JSON grammar for `.conf` & `.preset` files. Custom grammar for `.block`, `.item`, `.list`, `.page`, and `.region` files extends HTML.

I'll add SquareSpace's icon to the font (so users can select it with their stylesheets), but I'd rather not assign it to extensions that generic... something that looks plain but visibly template-related will do...

**Comment by Alhadis** [comment]
Right, done. There won't be generic icon-designs done from our end, because that's exactly why the package is bundled with [Font Awesome](http://fontawesome.io/cheatsheet/). Out of 675 pictographs, as well as GitHub's [Octicons](https://octicons.github.com/), you're pretty damn likely to find something that resembles what you need.

You can find steps for [customising icons here](https://github.com/file-icons/atom#customisation).
