### ISSUE TITLE
Will media files be candidate for this project?

### ISSUE THREAD

**Issue by Kimi-Arthur** [file-icons/source#12]
This icon style is pretty cool! Great!

Just wondering whether media files' icons fit for this project, say .mkv, .avi, .mp4, .flac etc.

Or even other file types in general.

If not, any idea which project has similar style of file icons like this project?

**Comment by Alhadis** [comment]
The [`file-icons`](https://github.com/file-icons/atom) package already includes icons for media files:

<img src="https://cloud.githubusercontent.com/assets/2346707/24861619/c82ab974-1e3c-11e7-9ae6-4642e6a418a1.png" width="144" alt="Figure 1" />

These are provided by one of [the other icon-fonts](https://github.com/file-icons/atom#icon-reference) bundled with the package. We don't add duplicate icons to this font: its size would grow out of control very, very quickly.

**Comment by Kimi-Arthur** [comment]
Sorry to trouble again, but which one specifically is providing the "media.avi", "media.flac"? I opened the four links of them, but none seems to provide these.

**Comment by Alhadis** [comment]
Oh wait, [it's here](https://github.com/file-icons/source/blob/master/svg/Video.svg). Sorry, my fault.

You can also find a list of icons the package uses [here](https://github.com/file-icons/atom/blob/master/styles/icons.less).

**Comment by Kimi-Arthur** [comment]
Ah, I see. So it's actually a generic icon with different coloring.
Thanks for the information!
