### ISSUE TITLE
Add Browserslist file icon

### ISSUE THREAD

**Issue by ai** [file-icons/source#16]
Hi. Thanks for package.

[`browserslist`](https://github.com/ai/browserslist) is a config to describe what browsers do you support in current project. Autoprefixer, next version of `babel-preset-env` and ESLint and Stylelint plugins support it.

So I think it is pretty popular thing.

Few months before project got logo: https://github.com/ai/browserslist/blob/master/logo.svg

@Alhadis should we add its icon to plugins?

**Comment by Alhadis** [comment]
Hey there,

Certainly. Are you able to tell me what filenames (or file extensions) its icon should be applied to?

**Comment by ai** [comment]
`browserslist` and `.browserslistrc`

**Comment by Alhadis** [comment]
Done! Thank you!

It'll be featured in the next package release. =)
