### ISSUE TITLE
Suggestion: Add Moment.js

### ISSUE THREAD

**Issue by Dargmuesli** [file-icons/source#17]
Website: http://momentjs.com/
Icon: http://jquery-plugins.net/image/plugin/moment-js.jpg
Regex for Atom: `/^moment(-with-locales)?(\.min)?\.js$/i

**Comment by Alhadis** [comment]
Would Font Awesome's [clock icon](http://fontawesome.io/icon/clock-o/) be sufficient?

**Comment by Dargmuesli** [comment]
Yes, thanks :)
