### ISSUE TITLE
Suggestion: Add Moment-Timezone.js 

### ISSUE THREAD

**Issue by Dargmuesli** [file-icons/source#18]
Website: http://momentjs.com/timezone/
Icon: [githubusercontent](https://camo.githubusercontent.com/9be5dbc77bacffc05144ca512d117009c22b10d4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313036323930342f313034333237302f62623334313963362d306666612d313165332d383038322d3235343139323938333434372e706e67)
Regex for Atom: `/^moment-timezone(-with-data)?(-\d{4}-\d{4})?(\.min)?\.js$/i`

**Comment by Alhadis** [comment]
\*sigh* I've never *rejected* a user's request for an icon like this, so I'd feel like a dick for doing so.

I've added the icons, but please avoid requesting library icons in future. I'd rather not make a habit of this...

**Comment by Dargmuesli** [comment]
Ok, thank you very much. If that's against your principle you wouldn't have needed to add this. Now, I feel like a d* too for requesting that ;)

**Comment by Alhadis** [comment]
Sorry for bumping an old issue, but I've officially abolished this:

> please avoid requesting library icons in future

We have icons for operating systems, frameworks, libraries, languages, and everything in between. Moreover, this font is being used by projects unrelated to Atom, so I'm officially welcoming icons for libraries.  =)

Go nuts.
