### ISSUE TITLE
Question: Add Prism.js?

### ISSUE THREAD

**Issue by Dargmuesli** [file-icons/source#20]
Does it make sense to add [prism.js](http://prismjs.com)? The icon is more or less a simple triangle...

**Comment by Alhadis** [comment]
No, sorry.

I'd also prefer to avoid adding too many library/plugin icons, as it's a slippery slope that could end up bloating this font with the icons of literally any JS project that has a logo.

To be honest, adding icons for popular frameworks and libraries was essentially just making use of [icons that were already bundled in another font](https://github.com/file-icons/DevOpicons/blob/master/charmap.md). I recall a few more were added after that, but this isn't something I'd like to make a habit of...

**Comment by Dargmuesli** [comment]
Ok, that's alright. I think that moment.js is similar to chart.js and materialize regarding fame, dragula.js is less known.

**Comment by Alhadis** [comment]
[At one point](https://github.com/file-icons/source/commit/0efc72c011925a6e7f055133bb0ac04d7cba199d), I was contemplating adding icons for general libraries and frameworks. However, I later decided against it for the reasons I just described.
