### ISSUE TITLE
Update Browserslist icon

### ISSUE THREAD

**Issue by ai** [file-icons/source#23]
@Alhadis thanks for quick response to [previous PR](https://github.com/file-icons/source/issues/16).

Our designer @antiflasher make better icon for low-res: https://github.com/ai/browserslist/blob/master/icon.svg

Could we update it in package?

**Comment by Alhadis** [comment]
Hey @ai,

I've included it, but you'll need to wait until the next release before you can see it, I'm afraid.

Thanks!
