### ISSUE TITLE
Icon Request: Firebase Bolt 

### ISSUE THREAD

**Issue by maticzav** [file-icons/source#26]
Icon for `*.bolt` Firebase rules files.

**Comment by Alhadis** [comment]
Ahhh, wrong repository, my friend. =) There's [already an icon](https://github.com/file-icons/source/blob/master/svg/Firebase.svg) for Firebase, so this falls under the category of _"adding support for-"_. Which I've just [gone and done](https://github.com/file-icons/atom/commit/f53f701a55c99bd42f9df9e32ff86d5b07bf5cf1).

Thanks!

**Comment by maticzav** [comment]
Ah I see, sorry for the confussion and thanks you so much! 

Although I think (would guess) there's a different [icon](https://github.com/firebase/bolt/blob/master/docs/images/flash.png) for .bolt files, the one that firebase-bolt repo uses, shouldn't that one be used?

**Comment by Alhadis** [comment]
Ugh, you're right. I admit I didn't check...

I'll trace an icon for it, although to minimise the object store of this repository, I won't regenerate the actual icon-fonts until it's time to cut a new release.

Sorry about that...

**Comment by maticzav** [comment]
Sure! Thank you so much!
