### ISSUE TITLE
Icon request: pipenv

### ISSUE THREAD

**Issue by jacobmischka** [file-icons/source#27]
Adding the [pipenv icon](http://docs.pipenv.org/en/latest/_static/pipenv.svg) for usage with `Pipfile` and `Pipfile.lock` would be really neat. Thank you!

http://docs.pipenv.org/en/latest/

![pipenv](http://docs.pipenv.org/en/latest/_static/pipenv.svg)

**Comment by Alhadis** [comment]
Easy! On it. =)

**Comment by Alhadis** [comment]
Alright mate, done. Haven't regenerated the fonts yet; I aim to cut a new release sometime today or tomorrow, so I'll rebuild it then. Cheers!

**Comment by jacobmischka** [comment]
Thanks, impressively quick work as always!

**Comment by Alhadis** [comment]
Oh! BTW, I forgot to ask: do you have any thoughts on [`file-icons/atom#629`](https://github.com/file-icons/atom/issues/629) at all? =)

**Comment by Alhadis** [comment]
Eep, sorry for the wait.

This feels like the [oddest release](https://github.com/file-icons/atom/releases/tag/v2.1.10) yet.

**Comment by jacobmischka** [comment]
Ha, no worries, thanks!
