### ISSUE TITLE
Icon request: pypi

### ISSUE THREAD

**Issue by codefo** [file-icons/source#29]
I think we can use a [logo](https://pypi.org/static/images/logo-small.6eef541e.svg) from the new official [site](https://pypi.org/) for this icon.

**Comment by Alhadis** [comment]
Hey @codefo,

What filenames or file extensions would the icon be associated with?

**Comment by codefo** [comment]
Hi @Alhadis, Python community doesn't have a standard filename for storing dependency list as `package.json` in node.js 👎. 
But many developers stores their dependencies in `requirements.txt` file (haha it's just `.txt` 🤦‍♂️ )
I also using a `requirements.in` filename for [`pip-compile`](https://github.com/jazzband/pip-tools#without-setuppy) tool.

So I think right regexp for this case is something like this `requirements(.*).(txt|in)` (it also includes  `requirements.test.txt` etc.)

**Comment by Alhadis** [comment]
Got it, then! 👍 Will add now.

Should we include `.text` as a possible variation in ``requirements.txt` files?

**Comment by codefo** [comment]
I didn't saw it before in any repos

**Comment by Alhadis** [comment]
Sorry for the wait...

It might be better to restrict this icon to `requirements.in` only, as the risk of misidentification is too high for `requirements.txt` (imagine how many projects have a text file named `requirements`).

**Comment by codefo** [comment]
@Alhadis  yep, I understand your concerns. 
It's funny but true, while I'm googling in which files Python developers stores their dependencies, I found a new official tool for package management. It's call [`Pipenv`](http://docs.pipenv.org/en/latest/) and it uses a [`pipfile`](https://github.com/pypa/pipfile) format, just like the old version of Ruby bundler.
So I think we can drop `requirements.txt` support, and start using `Pipfile` and `Pipfile.lock` for this icon 👍

**Comment by Alhadis** [comment]
Hrm, `Pipfile`...? 🤔 We already added an icon for that in #27:

<img src="https://camo.githubusercontent.com/cf6f0cacc777799984e5267d7e96853b750882aa/68747470733a2f2f63646e2e7261776769742e636f6d2f66696c652d69636f6e732f736f757263652f6d61737465722f7376672f506970656e762e737667" width="256" height="256" valign="bottom" />

Is that not the correct icon to display for `Pipfile` resources?

**Comment by codefo** [comment]
Ah, sorry I've missed it. Thanks for your effort!

**Comment by bersace** [comment]
There is pyproject.toml, which is actually official (it has a PEP). https://www.python.org/dev/peps/pep-0518/

**Comment by Alhadis** [comment]
@bersace Which icon would you recommend we use for `pyproject.toml` files?

**Comment by bersace** [comment]
@Alhadis actually, Config-Python should do the trick.

**Comment by Alhadis** [comment]
Added in file-icons/atom@9ad8fc4, thanks!
