### ISSUE TITLE
Icon request: Rust

### ISSUE THREAD

**Issue by dawsonfi** [file-icons/source#30]
I think we can use the [logo](https://www.rust-lang.org/logos/rust-logo-blk.svg) from the oficial website.

This icon would be associated to all `.rs` files.

There's also the `Cargo.toml` file, that is the package manager for rust, who could have this [logo](https://crates.io/assets/Cargo-Logo-Small-c39abeb466d747f3be442698662c5260.png) from the oficial website.

**Comment by dawsonfi** [comment]
Looks like we already have it, sorry :(

**Comment by Alhadis** [comment]
Haha, don't worry, mate! This has actually happened several times, now. 😀 

I'll get around to rewriting the `READMD.md` someday... 😞
