### ISSUE TITLE
Icon Request: HashiCorp Nomad

### ISSUE THREAD

**Issue by jrasell** [file-icons/source#31]
Hi; firstly thanks for all the work on the project! I find it really useful and it improves the Atom UI massively.

I work very often with Nomad job specification files which I store; and are documented to use, a `.nomad` file extension. 

Would it be possible to add this using [this](https://cdn.worldvectorlogo.com/logos/nomad-2.svg) vector logo?

**Comment by Alhadis** [comment]
Hey @jrasell, 👋

I'll see how I fare, but that "N" in the centre might make dealing with the brighter/greener side somewhat interesting. :thinking: I don't think the Gestalt Effect is goanna help here...

**Comment by jrasell** [comment]
Thanks very much for the work @Alhadis
