### ISSUE TITLE
Icon request: Robot for robot.txt

### ISSUE THREAD

**Issue by ericcornelissen** [file-icons/source#32]
I wanted to add an icon for `robot.txt` files to the Atom package, but there is no robot icons in the existing fonts (as far as I know at least)(there is [hubot in octicons](https://octicons.github.com/icon/hubot/), but I don't think it should be used for this)

Since the [the official(?) website](http://www.robotstxt.org/) does not really have a proper icon to use for this, I would suggest just using a random but iconic robot icon, for example [this one](https://thenounproject.com/term/robot-head/771010/) (which has a license!).

For clarity, this icon would only be associated to `robot.txt` files.

Throughts?

**Comment by Alhadis** [comment]
> there is hubot in octicons, but I don't think it should be used for this

Hrm, any particular reason you think it shouldn't?

While I'm not averse to adding "unofficial" icons for filetypes which lack them, this would feel like overkill to be honest...

**Comment by ericcornelissen** [comment]
> Hrm, any particular reason you think it shouldn't?

The main reason I did think that is because [Hubot](https://hubot.github.com/) is a Github product. But if you think it is okay to use it for the specified purpose, I'll have a go at a PR in file-icons/atom 🙂
