### ISSUE TITLE
Icon Request : Avro

### ISSUE THREAD

**Issue by ghivert** [file-icons/source#33]
Hi! First, thanks for your work, it's awesome!

I'm dealing with Avro schema files those times, and it's not in the package… Maybe we could use the  logo from [the site](https://avro.apache.org/)?

**Comment by Alhadis** [comment]
Hey @ghivert,

So sorry it's taking an eternity to get back to you. 😞  My MacBook died the other week, and 4-5 hours of commuting each day has suddenly become extremely unproductive...

The [logo](https://avro.apache.org/images/avro-logo.png) on Avro's site is in PNG format, so I'll need to trace it (which naturally requires me to have a working computer and graphics editor...). Do you know if there's an SVG version of their logo anywhere?

**Comment by ghivert** [comment]
Hey!

No problem, it's not a urgent problem! ;)

I don't know about an SVG format neither. There's only the PNG version on the internet...

**Comment by Ekidoxx** [comment]
I guess this could help you guys: https://github.com/vscode-icons/vscode-icons/pull/1145

**Comment by Alhadis** [comment]
Hey @Ekidoxx, thanks for that! :green_heart: I'll probably need to touch it up a bit so it's easier to make out at smaller size (particularly the gap inside the triangle's border). Thank you!

**Comment by Ekidoxx** [comment]
No problem. Landed here by an accident, and randomly thought that out of boredom I'd try to find the svg file, so I'm glad I could help ^^,
