### ISSUE TITLE
Travis ci icon

### ISSUE THREAD

**Issue by PurpleBabar** [file-icons/source#34]
Hi :) 
Can you change the travis icon to puth the one they have now  ?
I have a link to that :) https://www.dropbox.com/s/tmzyv2h69cgjxu8/travis-ci%20%281%29.svg?dl=0

thanks a lot :D

**Comment by Alhadis** [comment]
Originally, `file-icons` *did* use Travis CI's logo as an icon. Users found the icon difficult to distinguish at such a small size, and in some cases, it was almost unrecognisable. Using the letter `T` instead proved to be a satisfactory alternative.

This was a long time ago, and the original Travis icon that was originally used was dropped from the icon-font before my involvement with the project started. However, you can still use the SVG that you've provided by adding the following snippet to your stylesheet:

~~~less
.travis-icon::before {
	content: "";
	background: url("/PATH/TO/YOUR.SVG") center no-repeat;
	background-size: contain;
}
~~~

I'm unable to access Atom at the moment, so I can't double-check the code above to verify that it displays correctly. So if you have any further problems adding it, please let me know. =)

By the way, you don't need to upload SVG files to Dropbox or any other file uploading service. =) You can embed the SVG's source code with Markdown:

~~~markdown
```svg
*copy+paste*
```
~~~
Only upload the file if the SVG is truly massive in size (over 1.0 MBs, for example). You'll sometimes find SVGs that have been improperly exported from graphics editing software, which can sometimes grow to ridiculous sizes.

**Comment by PurpleBabar** [comment]
Hi :) 

Thanks for the answer, I will believe you on the size of the icon and save some troubles for my eyes :D 

Cheerz
