### ISSUE TITLE
Icon Request: project.pros

### ISSUE THREAD

**Issue by edjubuh** [file-icons/source#36]
Thanks for this great package! I maintain a development environment built on Atom called [PROS](https://pros.cs.purdue.edu). Our users install your package by default to get great looking file icons. Our users have a `project.pros` file which maintains some information about their projects and I currently do some dirty hacks to get our logo replaced with the default file icon. Would it be possible for you to make our file icon part of the file-icons source?

This is the logo I've been using:
```svg
<svg xmlns='http://www.w3.org/2000/svg' width='89' height='90' viewBox='0 0 89 89.6'><polygon points='73.4 35.4 88.6 48.5 44.4 87 44.4 86.9 44.4 87 0.4 48.7 15.7 35.5 44.5 77.7 ' class='a'/><polygon points='22.5 22.2 23.4 23.7 65.6 23.7 66.5 22.2 ' class='a'/><polygon points='32.5 50.5 27.5 36 13.3 28.1 ' class='a'/><polygon points='56.5 50.7 61.6 36 75.6 28.2 ' class='a'/><path d='M44.5 2.6L7.1 19.4h13.4l2.8 4.3h42.2l2.8-4.3h13.4L44.5 2.6zM47.4 12.9l-2.9 1.5 -2.9-1.5V9.9l2.9-1.5 2.9 1.5V12.9z' class='a'/><path d='M74.8 28.1H14.1l0.1 0.1 18.5 2.8 -0.3 19.5 -2.4-2.8 13.7 16.8v-18.3c0-0.3 0.3-0.6 0.6-0.6h0.3c0.3 0 0.6 0.3 0.6 0.6v18.3l11.4-14 -0.1 0.1 -0.3-19.6L74.6 28.4 74.8 28.1zM44.5 42.8c-0.6 0-1.2-0.5-1.2-1.2 0-0.6 0.5-1.2 1.2-1.2 0.6 0 1.2 0.5 1.2 1.2C45.6 42.2 45.1 42.8 44.5 42.8zM44.5 37.8c-0.6 0-1.2-0.5-1.2-1.2 0-0.6 0.5-1.2 1.2-1.2 0.6 0 1.2 0.5 1.2 1.2C45.6 37.2 45.1 37.8 44.5 37.8zM44.5 32.6c-0.6 0-1.2-0.5-1.2-1.2s0.5-1.2 1.2-1.2c0.6 0 1.2 0.5 1.2 1.2S45.1 32.6 44.5 32.6z' class='a'/></svg>
```

We use `#E6B85C` or a close gold color typically.

**Comment by Alhadis** [comment]
👋 Hey @edjubuh,

Thanks for the kind words! I'll add it to the package's repertoire. =) It'll be available with the next release of the package (which comes every so often, depending on how many changes are pending).

> I currently do some dirty hacks to get our logo replaced with the default file icon.

What sort of hacks? Do you mean something like this?

~~~css
.icon[data-name="project.pros"]::before{
	background: no-repeat 50% 50% url("logo.svg");
	background-size: contain;
	top: 3px;
	width: 16px;
	height: 16px;
	content: "";
}
~~~

**Comment by edjubuh** [comment]
Not sure if I wanna show ha

https://github.com/purduesigbots/pros-atom/blob/master/styles/purdueros.less#L76-L103
