### ISSUE TITLE
Icon Request: tsconfig.json and jsconfig.json

### ISSUE THREAD

**Issue by bennypowers** [file-icons/source#38]
☝️ 🙏

**Comment by Alhadis** [comment]
Hey @bennypowers,

Could you be a bit more specific? What sort of icons should these files use?

**Comment by Alhadis** [comment]
Nudging @bennypowers.

**Comment by bennypowers** [comment]
OHAI!

So I poked around and noticed that there's no logo for ts language server.

Maybe the ts square superimposed on a stack of json pancakes? 🤷‍♂️ Or even blue json à la app.webmanifest?

**Comment by Alhadis** [comment]
Sorry mate. I'm happy to design new icons when there's a binding reason to do so (such as the test-file icons for `-spec.js`, et al). If I were to make one for `[tj]sconfig.json` files, it becomes harder for me to explain to others why we don't have improvised icons for [134 generic data formats](https://github.com/file-icons/atom/blob/d2571f9a36e685e6f95d7fb6fa8fbdc1b0213694/config.cson#L1766-L1900), let alone any JSON file which serves as a type of manifest.

[Something similar](https://github.com/file-icons/source/issues/20) happened last year regarding icons for specific JavaScript libraries (as in, for the actual JS files themselves, not a related config file). It taught me why making adhoc exceptions leads to awkward complications later on...

Hopefully this makes sense to you. =)

> Or even blue json à la app.webmanifest?

You can use your stylesheet. :wink:

~~~css
.icon[data-name="tsconfig.json"]::before {
	color: #00c; /* Or whichever shade of blue you prefer. */
}
~~~
