### ISSUE TITLE
.fasta icon (and related)

### ISSUE THREAD

**Issue by Benjamin-Lee** [file-icons/source#41]
[FASTA](https://en.wikipedia.org/wiki/FASTA_format) format (and its relatives) are used heavily in computational biology. Could we please get a DNA symbol for it?

Affected formats are:
* .fasta
* .fa
* .fastq
* .fq
* .fna
* .faa
* .ffn
* .frn
* .sam

**Comment by Alhadis** [comment]
Not a problem! 😉 Would this be okay...?

<img src="https://user-images.githubusercontent.com/2346707/42131996-fc5d9480-7d51-11e8-93a3-44dea204976b.png" alt="Figure 1: 16&times;16" width="16" valign="top" /> <img src="https://user-images.githubusercontent.com/2346707/42131996-fc5d9480-7d51-11e8-93a3-44dea204976b.png" alt="Figure 1: 512&times;512" valign="top" />

**Comment by Benjamin-Lee** [comment]
Perfect!

**Comment by Alhadis** [comment]
Awesome. Thanks for letting me know! 😁

I'll probably cut a release in the next couple of days, so I'll regenerate the icon files then. 😉
