### ISSUE TITLE
Icon for PICO-8 files

### ISSUE THREAD

**Issue by tobiasvl** [file-icons/source#43]
Hey, here's an icon for PICO-8 files with the extension `.p8`: [PICO-8 icon](https://gist.github.com/tobiasvl/34cf785528d2a6003ad6002097ab0e31)

**Comment by Alhadis** [comment]
No problem, added! 😀 Thanks for being a part of this!

**Comment by Milad3518** [comment]
Thanks for your Help.🙏🙌🖐

‫‪John Gardner‬‏ <‪notifications@github.com‬‏> در تاریخ جمعه ۱۰ اوت ۲۰۱۸
ساعت ۲۲:۰۶ نوشت:‬
