### ISSUE TITLE
Fountain.io icons

### ISSUE THREAD

**Issue by spookyUnknownUser** [file-icons/source#46]
Wondering what it would take to add the https://fountain.io icons to the package. All I can find on their website is .pngs and I'm assuming we would need a svg?

**Comment by Alhadis** [comment]
Yes, but I can easily trace one, that's no problem. =)

When you say "icons", do you mean there's more than one? I can only see their logo:

<img src="https://fountain.io/_img/fountain-sign-32.png">

**Comment by spookyUnknownUser** [comment]
Yeah that one would be great!

**Comment by spookyUnknownUser** [comment]
Wow can't believe how fast that was! Thank you so much.
