### ISSUE TITLE
Suggestion: Add Scilla icon

### ISSUE THREAD

**Issue by man15h** [file-icons/source#47]
Lang: https://scilla.readthedocs.io/en/latest/index.html
Icon: https://scilla.readthedocs.io/en/latest/_images/scilla-logo-color-transparent.png
File types: .scilla

Thanks

**Comment by man15h** [comment]
UPDATE: Here is the SVG version of the icon: https://www.dropbox.com/s/fv1c4tfa1bsmur6/image2vector.svg?dl=0

**Comment by Alhadis** [comment]
Done. Thank you!
