### ISSUE TITLE
Suggestion: Icons for Xcode project files

### ISSUE THREAD

**Issue by aaronsky** [file-icons/source#48]
Hey! I'm wondering what would be involved in creating icons for Xcode project files/packages. I use VS Code for managing a large iOS monorepo and I prefer to work there instead of Xcode. Unfortunately, `.xcworkspace` and `.xcodeproj` packages are represented as folders and don't stand out against the other folders in the project. In addition, Xcode-specific file types like those in the following list are ascribed the plain-text icon, since (naturally) no one else recognizes them. 

Apple has icons for the following that should probably be matched in some way:

* `.xcworkspace`
* `.xcodeproj`

Apple does not have icons for any of these, but having icons for each of these file types (which can all use the same icon if preferred) would make it easier to distinguish those files against others:

* `.pbxuser`
* `.xccheckout`
* `.pbxproj`
* `.xcuserstate`
* `.xcscmblueprint`
* `.xcscheme`
* `.plist`
* `.xcsettings`
* `.xcworkspacedata`

Let me know if I need to provide any more information. I don't have much in the way of Illustrator knowledge but I will pitch in where I can.

**Comment by Alhadis** [comment]
Hey @aaronsky, :wave:

We actually [have an icon](https://github.com/file-icons/DevOpicons/blob/master/svg/appstore.svg) for `.xcworkspace` and `.xcodeproj` files already, it just needs to be associated with them. Would that work?

I'm not responsible for the VSCode version of File-Icons (only the Atom version), so you might have to submit an issue to [`file-icons/vscode`](https://github.com/file-icons/vscode/issues) before updates will be live.

Apologies for the slow response, been away from computers for the last week.

**Comment by Alhadis** [comment]
I've added support for this in the Atom package. Support will land in the VSCode port once a new release is cut for the Atom version and @DanBrooker's updated the VSCode port. 👍

FYI, I've omitted `.plist` files from the list of Xcode-related files, as it's not strictly Xcode-specific. It's (usually) just a plain XML file, so it shares the XML file-icon.

**Comment by aaronsky** [comment]
Wow, thank you!
