### ISSUE TITLE
Haskell icon

### ISSUE THREAD

**Issue by boothead** [file-icons/source#51]
Hi could we have a Haskell icon please? It seems to be available here: https://github.com/file-icons/DevOpicons/blob/master/charmap.md as `\E677`

What needs to happen if an icon isn't in that list? I'd also like a nix icon, but that one doesn't seem to be there.

*edit* This is the nix logo: https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg

**Comment by Alhadis** [comment]
Erh, what's the point in (re-)adding an icon we already have? Can't you use DevOpIcons for that purpose?

**Comment by Alhadis** [comment]
We [already have](https://github.com/file-icons/source/blob/master/svg/Nix.svg) a Nix icon, too. It's even [listed in the character map](https://github.com/file-icons/source/blob/master/charmap.md#e99a).

Closing as there's really nothing to do here.
