### ISSUE TITLE
Icon Request: Gravit Designer

### ISSUE THREAD

**Issue by YhvrWasTaken** [file-icons/source#52]
Hello! Would you mind adding icons for [Gravit Designer](https://designer.io) files? I use them sometimes, and it's kind of strange with them not having an icon. Their extension is `*.gvdesign`. Thanks!

**Comment by Alhadis** [comment]
Done! Sorry for the slow response. haven't been well lately. 😞

Will regenerate the repo's font-files when the next package release is cut. 👍
