### ISSUE TITLE
Icon request: digdag

### ISSUE THREAD

**Issue by yamarkz** [file-icons/source#53]
Hi! I'm using work flow engine [Digdag](https://www.digdag.io/). 
which uses the .dig file, as scheduler service for my project, would it be possible for you to add an icon for that? `.dig`

**Comment by Alhadis** [comment]
Done, thanks! You'll see it in the next package release, which happens roughly once-a-month. 👍

**Comment by yamarkz** [comment]
thanks! great work 👍
