### ISSUE TITLE
Icon request: svelte

### ISSUE THREAD

**Issue by sgomes** [file-icons/source#54]
Hi there!

Would it be possible have an icon for `.svelte` files, which are used by the [Svelte framework](https://svelte.dev)?

The logo for the project is [available as an SVG on their repository](https://github.com/sveltejs/svelte/blob/master/site/static/svelte-logo.svg).

Thanks in advance! 🙂

**Comment by Alhadis** [comment]
Hey mate! :wave: Sorry for the slow response.

No problem, I'll add it later tonight. :+1:

**Comment by sgomes** [comment]
> Hey mate! 👋 Sorry for the slow response.
> 
> No problem, I'll add it later tonight. 👍

Wait, you consider this slow?

Thank you so much! 😄

**Comment by Alhadis** [comment]
I have a huge-ass commit staged locally with over 20+ new icons, so I'll roll Svelte's icon into the commit. I have to update the [filetype database](https://github.com/file-icons/atom/blob/350e6c49acdf7fc11a0a8f96051f7ac252f57b3a/config.cson) in a separate repository, so syncing stuff is... messy.

(Having two update *two* different repositories for each new icon I add has been the bane of this project since my involvement…)

**Comment by sgomes** [comment]
> (Having two update _two_ different repositories for each new icon I add has been the bane of this project since my involvement…)

That does sound messy... Have you considered folding everything into a single monorepo, using [lerna](https://lerna.js.org/)? It's somewhat involved to set up, but ends up paying off in the long run. It also tends to be a little less messy than git submodules.

**Comment by Alhadis** [comment]
Unfortunately, long-term scope of this project will involve many editors and many languages, not all of which are web-related. Vim, Emacs, browser extensions (for GitHub, GitLab, et al), and Lord knows what else.

Font generating is currently being assembled manually using [IcoMoon](https://Icomoon.io/app/#/select). Slow, error-prone, and worst of all, impossible to roll into a build-step. FontForge will be involved sooner or later, which involves Python... and installing FontForge... and lots of other variables. 😞

All of this falls well outside the scope of NPM. So tying everything together will involve looots of planning.

**Comment by sgomes** [comment]
Ah, I see you have your work cut out for you, then 😞 Hope you manage to find a build system that works for all of those use-cases!

**Comment by Alhadis** [comment]
There we are:

<img src="https://user-images.githubusercontent.com/2346707/56681536-ddcd5280-670c-11e9-891e-6c12c907bdc3.png" alt="Figure 1" />

**Comment by sgomes** [comment]
Woohoo, thank you so much! 😀 🎉
