### ISSUE TITLE
Icon request: Fexl & Scratch 2/3 Save

### ISSUE THREAD

**Issue by YhvrWasTaken** [file-icons/source#55]
At this point, I'm just looking around my filesystem for files without icons. [Fexl- *.fxl](https://fexl.com/) [Scratch 2 - *.sb2](https://scratch.mit.edu) [Scratch 3 - *.sb3](https://scratch.mit.edu)

**Comment by Alhadis** [comment]
> At this point, I'm just looking around my filesystem for files without icons

Digging through unfamiliar directories or codebases is actually the best way to discover formats you're missing. Keep it up. 😉

Moved the issue here as that's ideally where new icon requests should be filed (though the `file-icons/atom` repository continues to be updated separately…)
