### ISSUE TITLE
Please add icon for Caddy web server

### ISSUE THREAD

**Issue by codefo** [file-icons/source#7]
Caddy is a simple but powerful web server, it would be nice if we can add this icon into Atom plugin for his config file.
https://caddyserver.com/

**Comment by Alhadis** [comment]
Hey mate, sure thing! Are there any file extensions or filename associations we could be applying this icon to? =)

**Comment by Alhadis** [comment]
Added it, but please let me know what filetypes to assign this to.

**Comment by codefo** [comment]
@Alhadis thank you 👍 By default Caddy uses `Caddyfile` for configuration, without any extension.
