### ISSUE TITLE
Better icon for `.yaml` files

### ISSUE THREAD

**Issue by andmos** [file-icons/source#8]
I notice that `.yml` and `.yaml` files gets the [database symbol from Octicons](https://octicons.github.com/icon/database/) in my editor, which looks quite strange. I work with [Ansible](https://www.ansible.com/) which has many such files. I would like a more easy on the eyes version for YAML files than the database icon.. Googling around, I can't seem to find any "official" YAML icon, so I guess artistic freedom can be used here?

**Comment by Alhadis** [comment]
And what exactly would you suggest?

**Comment by andmos** [comment]
I'm not much of an artist, but in my mind i toyed with something like the Vim-logo, A larger 'Y' with 'ml' a bit smaller following it. Would something like that work?

**Comment by Alhadis** [comment]
Eh, I'm afraid not... It makes no sense to single YAML out when there are dozens of other plain-text data formats sharing the same icon. A plain-looking icon is decidedly more appropriate for representing such a commonplace format, too.

Remember you can always use your stylesheet to attach a custom icon for YAML files:

~~~less
.icon[data-name$=".yml"],
.icon[data-name$=".yaml"]{
	&:before{
		width: 1em;
		height: 1em;
		vertical-align: -10%;
		background: url("./some-icon.svg");
		background-size: contain;
	}
}
~~~

**Comment by andmos** [comment]
>A plain-looking icon is decidedly more appropriate for representing such a commonplace format.
I agree, but I don't think that icon should be a database-icon. But cool, I'm gonna make myself something. Thanks!

**Comment by Alhadis** [comment]
That's what I love most about Atom: if you're not 100% satisfied with any part of it, hack the shit out of it until you are. 👍 

I wish every program followed that philosophy. Seriously, I'm feeling handcuffed in other programs when I realise I can't tweak something in the UI, heh.

**Comment by dannyhanes** [comment]
@andmos Did you ever come up with something? Would love to have a yaml icon that isn't a database lol

**Comment by andmos** [comment]
@dannyhanes nothing I am satisfied with, no. I have been looking into other icon packs for something to shamelessly steal, but I haven't found anything that stands out to me. Feel free to give me a ping if you find something!

**Comment by Alhadis** [comment]
There's this logo here, whose graphics leave a lot to be desired:

<img src="https://raw.githubusercontent.com/yaml/www.yaml.io/master/img/logo-2x.png" width="221" alt="Figure 1" />

Then there're the sleeker-looking icons sourced from [YAML's more modernised look](http://billyzduke.net/storage/app/media/technologies/YAML-logo.svg):

<Img src="https://user-images.githubusercontent.com/2346707/32840225-2d0eaf00-ca6b-11e7-86ba-028193ca96fb.png" width="270" alt="Figure 2" />


As if that isn't enough, there's a *third* YAML icon floating around with varying colour choices:

<img src="https://user-images.githubusercontent.com/2346707/32840122-d509d5a0-ca6a-11e7-8d9a-76c6729a428b.png" width="300" alt="Figure 3" />


Now, I'm all for giving users a variety of icons to select from, but adding each of these icons with a variation or two just seems absolutely ridiculous to me. On the other hand, I have no knowledge of YAML's branding history, so unless somebody can tell me which icons to ignore and which to use, eh... 😕

**Comment by andmos** [comment]
Yeah, it would be nice if the project had an official logo or something. The homepage is.. well, yaml-style. http://yaml.org/

**Comment by Alhadis** [comment]
Right, screw it. I added a bunch of variants so people can choose the one they like best. If this looks silly and excessive, I agree. 😄 Thank the YAML folk for not being clear and consistent with their branding.

**Comment by andmos** [comment]
All right! The default was good enough for me @Alhadis, thanks for the effort!

**Comment by bilo-io** [comment]
wow ... this was an interesting read about an icon. 

Thank you! I was struggling to choose one for `.yml`
